- .rspec
- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
-Adds RSpec setup
-Adds shoulda matchers gem and setup
> adds rspec setup and shoulda matchers

- app/controllers/books_controller.rb
- app/models/book.rb
- app/views/books/index.html.erb
- db/migrate/20181205005327_create_books.rb
- db/migrate/20181205014353_add_year_to_books.rb
- db/schema.rb
- spec/features/user_sees_book_titles_spec.rb
- spec/models/book_spec.rb
Added feature test for book info 
Added model test for books
Added erb to the book index for views. 
closes #27
> Book index page#27

- app/controllers/books_controller.rb
- app/models/book.rb
- app/models/review.rb
- app/views/books/show.html.erb
- db/migrate/20181205193907_create_reviews.rb
- db/migrate/20181205194553_add_books_to_reviews.rb
- db/schema.rb
- spec/features/user_sees_book_page_spec.rb
- spec/features/user_sees_book_titles_spec.rb
- spec/features/user_sees_nav_bar_spec.rb
- spec/models/book_spec.rb
- spec/models/review_spec.rb
- spec/spec_helper.rb
Added feature test for book show page. 
Added review model test. 
Created reviews table. 
Added books relationship test. 
Added book show view. 
closes #22
> Book show page#22

- app/controllers/books_controller.rb
- app/views/books/index.html.erb
- app/views/books/new.html.erb
- config/routes.rb
- spec/features/user_sees_new_book_link_spec.rb
-Added feature tests for new book view
-Added erb to new book view with form 
-Need to merge so I can pull down maddie's most recent changes because my card incorrectly showed no pre-requisites, but I need the reviews table that we built
> Add new book#19

- app/controllers/books_controller.rb
- app/models/author.rb
- app/models/book.rb
- app/models/book_author.rb
- app/views/books/index.html.erb
- app/views/books/new.html.erb
- app/views/books/show.html.erb
- db/migrate/20181205014353_add_year_to_books.rb
- db/migrate/20181205212848_remove_year_from_books.rb
- db/migrate/20181205220548_remove_author_from_books.rb
- db/migrate/20181205221231_create_authors.rb
- db/migrate/20181205221727_create_book_authors.rb
- db/migrate/20181206012353_add_year_to_books.rb
- db/schema.rb
- spec/features/user_can_create_new_book_spec.rb
- spec/features/user_sees_book_page_spec.rb
- spec/features/user_sees_book_titles_spec.rb
- spec/features/user_sees_new_book_link_spec.rb
- spec/models/author_spec.rb
- spec/models/book_spec.rb
-Added changes to form to new book form allow multiple authors
-Creating a book also creates or finds author(s)
> New book contd#19

- app/controllers/authors_controller.rb
- app/views/authors/show.html.erb
- config/routes.rb
- spec/features/user_sees_all_books_in_author_spec.rb
Added author show page. 
closes #16
> Author show page#16

- app/models/book.rb
- spec/features/user_can_sort_all_books_spec.rb
Added feature test for book average rating. 
Added model test for book average rating. 
Still in process
> added feature and model tests for average rating

- app/controllers/books_controller.rb
- app/models/book.rb
- app/views/books/index.html.erb
- app/views/layouts/application.html.erb
- spec/features/user_can_see_sort_links_spec.rb
- spec/features/user_can_sort_books_spec.rb
-Added all links for sorting
-Average rating ascending works
-Model test passes for average rating ascending
-need to write model tests and model methods for the rest of the sorting methods
-all tests except for the sorting visual test passing
will continue on this card later.
> Book index sort#25

- app/models/book.rb
- spec/features/user_can_sort_books_spec.rb
- spec/models/book_spec.rb
Pushing to master before leaving for the day
> committing so maddie can leave

- app/views/authors/show.html.erb
- app/views/books/index.html.erb
- spec/features/user_can_visit_author_by_clicking_link_spec.rb
> Added links for authors to authors show page

- app/views/books/show.html.erb
- config/routes.rb
- spec/features/user_can_write_new_review_spec.rb
Added test for new review link
> Add review for book#18

- app/views/books/index.html.erb
- app/views/books/show.html.erb
- db/seeds.rb
- spec/features/user_sees_book_title_links_spec.rb
-Added link to all book titles
-Added model tests for seeing the links
closes #31
> Book title links#31

- app/controllers/reviews_controller.rb
- app/views/reviews/new.html.erb
- config/routes.rb
- spec/features/user_sees_a_form_for_new_review_spec.rb
> added for for new review

- app/controllers/reviews_controller.rb
- app/controllers/users_controller.rb
- app/models/review.rb
- app/models/user.rb
- app/views/books/index.html.erb
- app/views/reviews/new.html.erb
- db/migrate/20181208004529_create_users.rb
- db/migrate/20181208004650_add_users_to_reviews.rb
- db/schema.rb
- db/seeds.rb
- spec/features/user_can_sort_books_spec.rb
- spec/features/user_can_visit_author_by_clicking_link_spec.rb
- spec/features/user_sees_a_form_for_new_review_spec.rb
- spec/features/user_sees_book_page_spec.rb
- spec/models/book_spec.rb
- spec/models/user_spec.rb
-Added users table
-Added relationship between reviews and users
-added user model tests
-updated all tests with user dependencies 
-added users to seed file
-all tests passing
closes #18
> Creates users#18

- app/assets/stylesheets/application.css
- app/models/review.rb
- app/views/books/index.html.erb
- app/views/books/show.html.erb
- app/views/users/show.html.erb
- spec/features/user_can_sort_books_spec.rb
- spec/features/user_sees_book_page_spec.rb
- spec/features/user_sees_user_show_page_spec.rb
- spec/models/book_spec.rb
- spec/models/review_spec.rb
- spec/models/user_spec.rb
-Adds username links to all places where username shows up
-Added missing relationship belongs_to :books to review model and updated tests
-Added feature tests for username links
closes #29
> Username links#29

- app/controllers/reviews_controller.rb
- app/models/review.rb
- app/models/user.rb
- app/views/reviews/new.html.erb
- spec/features/user_can_sort_books_spec.rb
- spec/features/user_sees_a_form_for_new_review_spec.rb
- spec/features/user_sees_user_show_page_spec.rb
- spec/models/book_spec.rb
Added feature tests and validation of username uniqueness for each book's review. 
Had to change some test setups because there were user creating reviews on the same books multiple times. This has created some merge conflict.
> User names are unique#5

- app/assets/stylesheets/application.css
- app/controllers/books_controller.rb
- app/models/book.rb
- app/views/books/show.html.erb
- app/views/users/show.html.erb
- spec/features/user_sees_book_page_spec.rb
- spec/models/book_spec.rb
- spec/models/user_spec.rb
-Adds feature and model tests for book show stats: average rating, top reviews, and bottom reviews
-Adds stats content to book show page
-Adds basing styling to book show stats and user show page
-96% coverage
closes #21
> Book show stats#21

- app/assets/stylesheets/application.css
- app/views/home/index.html.erb
- spec/features/user_can_see_welcome_page_spec.rb
-Added feature test for home page welcome message and links
-100% coverage!
> adds feature test for home page message and links all tests passing

- app/controllers/authors_controller.rb
- app/controllers/books_controller.rb
- app/models/author.rb
- app/models/book.rb
- app/models/book_author.rb
- app/models/review.rb
- app/models/user.rb
- app/views/authors/show.html.erb
- app/views/books/show.html.erb
- spec/features/user_can_visit_author_by_clicking_link_spec.rb
-Added feature and model tests for deleting an author
-Added link to author show page to delete author
closes #8
> Author delete#8

- app/controllers/reviews_controller.rb
- app/models/review.rb
- app/views/users/show.html.erb
- spec/features/user_sees_user_show_page_spec.rb
> Delate book review#10

- app/assets/stylesheets/application.css
-Removed styling that broke the dropdown link
> removes styling that broke dropdown

- app/views/books/index.html.erb
- app/views/books/show.html.erb
- spec/features/user_sees_a_form_for_new_review_spec.rb
-Removed round from show pages 
-Changed form fills for selecting rating
> removes round from show pages all tests passing

- Gemfile.lock
- db/seeds.rb
-Removing bang operators from seed file to see if this fixes heroku issue
> removes bang operators from seed frile create methods

- README.md
- app/models/book.rb
- app/views/books/index.html.erb
- app/views/books/show.html.erb
- spec/features/user_sees_book_title_links_spec.rb
- spec/models/book_spec.rb
- spec/spec_helper.rb
-Added links to readme
-Rewrote average rating and sorting by reviews books methods to work for books without reviews
> Sort book no rating
